local speaker = peripheral.find("speaker")
local midi = require("/modules.midi")
local file = fs.open("./example_source/example.mid", "rb")
local midiData = midi.parseMidi(file, speaker)
file.close()
midi.play(midiData, speaker)